### ISSUE TITLE
numpy error while training

### ISSUE THREAD

**Issue by sunsetjesus** [AliaksandrSiarohin/first-order-model#95]
**command :** python run.py config/dataset_0.yaml --device_ids 0

**result :** 

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
usage: run.py [-h] --config CONFIG [--mode {train,reconstruction,animate}]
              [--log_dir LOG_DIR] [--checkpoint CHECKPOINT]
              [--device_ids DEVICE_IDS] [--verbose]

**Comment by sunsetjesus** [comment]
after upgrading numpy to 1.18.2 and executing the same command, console log is - 

Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from frames_dataset import FramesDataset
  File "/home/sqro2/Projects-Temp/A.I/first-order-model/frames_dataset.py", line 2, in <module>
    from skimage import io, img_as_float32
  File "/home/sqro2/.local/lib/python3.5/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/home/sqro2/.local/lib/python3.5/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/home/sqro2/.local/lib/python3.5/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

**Comment by AliaksandrSiarohin** [comment]
```python run.py   --config config/dataset_0.yaml --device_ids 0```

**Comment by sunsetjesus** [comment]
error still exists - 
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from frames_dataset import FramesDataset
  File "/home/sqro2/Projects-Temp/A.I/first-order-model/frames_dataset.py", line 2, in <module>
    from skimage import io, img_as_float32
  File "/home/sqro2/.local/lib/python3.5/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/home/sqro2/.local/lib/python3.5/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/home/sqro2/.local/lib/python3.5/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

**Comment by AliaksandrSiarohin** [comment]
Not related to this repository.

**Comment by sunsetjesus** [comment]
@AliaksandrSiarohin I've fixed it by upgrading scikit-image . I appreciate your quick response and help. thank you
